#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2019 ANSSI. All rights reserved.

cargo +stable fmt -- --check &> /dev/null
if [[ ${?} -ne 0 ]] ; then
    echo 'Please run `cargo fmt` first.'
    exit 1
fi
